### ISSUE TITLE
-std=c99 -Wpedantic unnamed structs/unions warning with GCC

### ISSUE THREAD

**Issue by ghost** [BareRose/dvector#1]
Hello again. This one is nice and light. Only one warning so far, but it appears in several places at the beginning of the library.

````
include/dvector.h:83:23: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  struct {DVTYPE x, y;};
                       ^
include/dvector.h:87:29: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
     struct {DVTYPE x, y, z;};
                             ^
include/dvector.h:88:33: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
     struct {vec2 xy; DVTYPE _z;};
                                 ^
````
etc.

**Comment by ghost** [comment]
Possible solution [here](https://stackoverflow.com/questions/20752551/working-with-a-union-of-structs-in-c). Would you either be open to the extra bloat or be willing to part with the unions?

**Comment by BareRose** [comment]
The unions are part of core functionality, and having to do awkward stuff like `v.data.x` defeats the purpose of having typedef'd vector types IMO.

What I would be okay with is conditionally dropping the unions like this:

```
typedef struct vec3 {
    DVTYPE x, y, z;
} vec3;
```

The condition could be a configuration parameter, for example `DVECTOR_NOUNION`. Feel free to make a pull request for this, but be sure it doesn't break any of the existing code (some of it relies on the unions IIRC). Finding a good solution for the matrix types could be tricky aswell. Might be necessary to add getter/setter functions for columns/rows, but those would be a nice feature to have eitherways. I don't mind function bloat if it's trivial getters/setters like `vec3GetXY` or equivalents. In general I'd much prefer `vec3GetXY(v)` over `v.bloat.xy`.

(BTW I'm extremely busy at the moment, which is why I didn't just make these changes myself. Just a heads up.)

**Comment by ghost** [comment]
Not function bloat, struct bloat. If the struct types are defined outside of the unions there should be no compiler warnings according to what I read.

**Comment by ghost** [comment]
I see what you mean with the unions. I did as you suggested and will PR it now. There is no `vec3GetXY`; the only new getters are `vec4GetXYZ` and `quatGetXYZ` as dvector never asks for `.xy` AFAIK. There is plenty of room before we hit 1000 lines, so more getters can be added.

The next feature on my list would be a `DVECTOR_DOUBLE_PRECISION` flag that changes `cosf`, `sinf` to `cos`, `sin`, etc. I use `double`s for all my matrix math in C++.
